### ISSUE TITLE
Put a non-SNAPSHOT version of the library up on Clojars

### ISSUE THREAD

**Issue by AdamSpitz** [jamesmacaulay/cljs-promises#1]
This is a great library - good fundamental idea, and it seems to work solidly. It'd be convenient if I could easily include it in my projects with a simple line in my project.clj.

**Comment by jamesmacaulay** [comment]
Done!

https://clojars.org/jamesmacaulay/cljs-promises

**Comment by arichiardi** [comment]
Hello folks! Sorry to write in a closed issue, I wanted to ask what is the status of this project.
I see there is a more up to date fork and I was wondering whether I should contribute there or here.

I am interested in adding self-host compatibility (lumo).
