### ISSUE TITLE
Comparison to core.async/promise-chan

### ISSUE THREAD

**Issue by theronic** [jamesmacaulay/cljs-promises#5]
Hi James, I see this project has been around for a while.

In the README, you say as part of the rationale that "Channels in core.async are ... inherently mutable." Did core.async/promise-chan exist when you made this? And would you use that or your lib?

**Comment by jamesmacaulay** [comment]
I don't think promise-chan existed when I made this package, but it looks like it doesn't quite do the same thing. This package is for doing interop with JS promises, while promise-chan creates a channel with somewhat similar semantics but doesn't do any JS interop. If you need to work with JS promises coming from another library, this package could still be useful and provide something that promise-chan doesn't.
